# generated by fastapi-codegen:
#   filename:  .\backend\express\geoapp.yaml
#   timestamp: 2023-07-18T11:19:46+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class ApiResponse(BaseModel):
    code: int
    type: str
    message: str


class ErrorType(BaseModel):
    code: str = Field(..., description='Error code')
    message: str = Field(..., description='Error message')


class PostMessage(BaseModel):
    message: str = Field(..., description='', example='generate image')


class PostLoadImage(BaseModel):
    message: str = Field(..., description='upgrade the images')
